print("-" *39)
print("|                                     |")        
print("|                                     |") 
print("|                                     |") 
print("|                                     |") 
print("|                                     |") 
print("-" *39)