print("-" *39)
print("|x = 35                               |")          
print("|                                     |")
print("|               x = 35                |")
print("|                                     |")
print("|                               x = 35|")
print("-" *39)